# coding: utf-8
"""


Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""

import math


def problem_45():

    def is_triangle(x):
        n = (math.sqrt(8*x + 1) - 1) / 2
        return n if int(n) == n else False

    def is_pentagonal(x):
        n = (math.sqrt(24*x + 1) + 1) / 6
        return n if int(n) == n else False

    def is_hexagonal(x):
        n = (math.sqrt(8*x + 1) + 1) / 4
        return n if int(n) == n else False

    i = 40755
    while True:
        i += 1
        if is_triangle(i) and is_pentagonal(i) and is_hexagonal(i):
            return i


print(problem_45())
