# To run:
#   ruby 2.rb
#
# Problem:
#   Each new term in the Fibonacci sequence is generated by adding the previous
#   two terms. By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#   By considering the terms in the Fibonacci sequence whose values do not
#   exceed four million, find the sum of the even-valued terms.


def solve
    prev, fib = 1, 1
    sum = 0

    while fib <= 4e6
        if fib % 2 == 0
            sum += fib
        end
        fib, prev = fib + prev, fib
    end

    sum
end

start = Time.now
result = solve
finish = Time.now

puts "#{result} in #{finish - start} seconds"
